name: Playwright Tests

on: [push]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Node (for Playwright)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Playwright dependencies via npx
        run: |
          npx --yes playwright@latest install-deps chromium
          npx --yes playwright@latest install chromium
      
      - name: Build and run tests
        run: mvn clean test
        env:
          CI: true
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            target/surefire-reports/
            target/**/*.png
          if-no-files-found: warn
          retention-days: 30