name: Java Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Run tests
        run: mvn clean test
      
      - name: Check test reports
        run: |
          echo "Checking for test reports..."
          if [ -d "target/surefire-reports" ]; then
            echo "Found surefire-reports directory"
            ls -la target/surefire-reports/
          else
            echo "No surefire-reports directory found"
            echo "Checking entire target directory:"
            ls -la target/ || echo "No target directory"
          fi
      
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-outputs
          path: |
            target/surefire-reports/
            target/site/
          if-no-files-found: warn
          retention-days: 30