name: Playwright Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    timeout-minutes: 30
    runs-on: [self-hosted, linux, x64]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
        
      - name: Install Playwright browsers
        run: |
          echo "Installing Playwright browsers..."
          npx --yes playwright@latest install-deps chromium
          npx --yes playwright@latest install chromium
          echo "Playwright installation complete"
        
      - name: Compile project
        run: |
          echo "Compiling project..."
          mvn clean compile test-compile
          echo "Compilation complete"
          echo "Test classes found:"
          find target/test-classes -name "*.class" -type f | wc -l
        
      - name: Run tests in headed mode
        run: |
          echo "Starting test execution in headed mode..."
          export DISPLAY=:99
          export HEADED=true
          mvn test -DfailIfNoTests=false
          echo "Test execution complete"
        env:
          CI: true
          HEADED: true
        
      - name: Display test results
        if: always()
        run: |
          echo "=== Test Results ==="
          if [ -d "target/surefire-reports" ]; then
            echo "Test reports found:"
            ls -la target/surefire-reports/
            echo ""
            echo "=== Test Summary ==="
            grep -h "Tests run:" target/surefire-reports/*.txt 2>/dev/null || echo "No test summaries found"
            echo ""
            echo "=== Detailed Results ==="
            for file in target/surefire-reports/*.txt; do
              if [ -f "$file" ]; then
                echo "--- $(basename $file) ---"
                cat "$file"
                echo ""
              fi
            done
          else
            echo "No test reports generated"
            echo "Checking target directory:"
            ls -la target/
          fi
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ github.run_number }}
          path: |
            target/surefire-reports/
            target/*.png
            target/test-classes/
          if-no-files-found: warn
          retention-days: 30
        
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false