name: Debug Tests

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Show project structure
        run: |
          echo "=== Project Structure ==="
          ls -la
          echo ""
          echo "=== Source Structure ==="
          find src -type f -name "*.java" | head -20
          echo ""
          echo "=== POM.xml Content (first 50 lines) ==="
          head -50 pom.xml
      
      - name: Compile project
        run: |
          echo "=== Compiling Project ==="
          mvn clean compile test-compile
          echo ""
          echo "=== Test Classes Found ==="
          find target/test-classes -name "*.class" 2>/dev/null | head -20 || echo "No test classes found!"
      
      - name: List available tests
        run: |
          echo "=== Running Maven Test List ==="
          mvn test -Dtest=* -DfailIfNoTests=false -X | grep -E "Running|Tests run:|BUILD"
      
      - name: Run tests with verbose output
        run: |
          echo "=== Running Tests with Full Output ==="
          mvn test -e -X > test-output.log 2>&1 || true
          echo "=== Last 100 lines of test output ==="
          tail -100 test-output.log
          echo ""
          echo "=== Checking for test reports ==="
          ls -la target/ || echo "No target directory"
          ls -la target/surefire-reports/ 2>/dev/null || echo "No surefire-reports"
      
      - name: Upload debug logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-logs
          path: |
            test-output.log
            target/
          if-no-files-found: warn